## Bonus Assignment

## Author : Jhansi Turumella

In [21]:
import numpy as np

In [26]:
# A is the array with the below elements and we are converting it to array
A = [3,1,2,4,3]
A_arr = np.array(A)
print(A_arr)
#type(A_arr)

[3 1 2 4 3]


In [20]:
print(A[::])

[3, 1, 2, 4, 3]


In [17]:
#Printing the length of array
length = len(A_arr)
print(length)

5


In [18]:
#Absolute difference of 2 arrays

def sub(a,b):
    subval = abs(a-b)
    return subval


In [19]:
#divi is the function which splits the array into 2 parts based on k value(in iteration)
def divi(x,k):    #x is the array, k is the incremental iteration from 1,2...9
    return (A_arr[:k],A_arr[k:])
    
    #for j in range(0,length):
        #return (A_arr[:k],A_arr[k:])  #Splitting into 2 arrays based on k values
diffarr = []                          # To store the absolute diff values in list
for i in range(1,length):             #Driver code for splitting
    arr1,arr2 = divi(A_arr,i)
    print(arr1,arr2) #ignoring this statement as we need not display splitting of array in iteration
    res1 = sum(arr1)                   # Sum of array1(arr1)
    res2 = sum(arr2)                   # Sum of array2(arr2)
    #print(res1, res2)
    subres = sub(res1,res2)            # calling absolute diff function to subtract arrays
    diffarr.append(subres)             # appending the abs diff values into list to compare
print('Absolute differences between arrays are {}'.format(diffarr))             # Printing the list of absdiff in list

print('Smallest absolute difference in the given array is {}'.format(min(diffarr)))  #printing the min value in the list which is out task
    

[3] [1 2 4 3]
[3 1] [2 4 3]
[3 1 2] [4 3]
[3 1 2 4] [3]
Absolute differences between arrays are [7, 5, 1, 7]
Smallest absolute difference in the given array is 1


In [ ]:
print()